CREATE TABLE `cprg104`.`SQL_ex` ( `id` INT(32) UNSIGNED NOT NULL , 
	`fname` VARCHAR(32) NOT NULL ,
	 `lname` VARCHAR(32) NOT NULL ,
	  `dob` TIMESTAMP NOT NULL ,
	   PRIMARY KEY (`id`)) ENGINE = InnoDB;